name: color_gram
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vibration: ^1.2.1
  url_launcher: ^5.0.3
  local_notifications:
  cupertino_icons: ^0.1.2
  path_provider: ^1.3.1
  sqflite: ^1.1.7+1
  fluttertoast: ^3.1.3
  font_awesome_flutter: ^8.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

